---
title: "Untitled"
format: html
---

```{r setup}

knitr::opts_chunk$set(echo = FALSE, fig.width=9, message = FALSE, warning=FALSE)

library(tidyverse)
library(sf)
library(readxl)
library(kableExtra)
library(flextable)
library(viridis)
library(scales)
library(janitor)
library(cowplot)
library(magick)
library(patchwork)
library(shadowtext)
library(showtext)
library(ggrepel)
library(terra)
library(tidyterra)
library(maptiles)
library(cowplot)
library(ggview)

# showtext_auto()

# font_add_google("Roboto", "roboto")

`%out%` <- Negate(`%in%`)

theme_set(theme_light())

options(scipen = 999)

```

# Data

## Geodata

```{r}

nepal_admin <- read_xlsx("./data/npl_admin_boundaries.xlsx", 
                         sheet = 7) |> 
  select(adm3_name, adm3_pcode, adm2_name, adm2_pcode, adm1_name, adm1_pcode)

affected_municipalities_wards <- read_xls("./data/Affected_wardsv2.xls") |> 
  janitor::clean_names() |> 
  select(adm1_pcode, 
         district = adm2_en, 
         adm2_pcode,
         municipality = adm3_en, 
         adm3_pcode, 
         ward = new_ward_n) |> 
  left_join(
    nepal_admin |> 
      distinct(adm1_name, adm1_pcode), 
    by = "adm1_pcode"
  ) |> 
  rename(province = adm1_name) |> 
  relocate(province, .before = adm1_pcode) |> 
  distinct(adm3_pcode, ward)

wards <- st_read("./data/shapefiles/npl_admn_ad4_py_s1_ocha_hp_wards.shp") |> 
  rename(ward = NEW_WARD_N) |> 
  janitor::clean_names() 

affected_wards <- read_xls("./data/Affected_wardsV2.xls") |> 
  janitor::clean_names()

adm3 <- st_read("./data/shapefiles/npl_admin_boundaries.shp/npl_admin3.shp")

adm2 <- st_read("./data/shapefiles/npl_admin_boundaries.shp/npl_admin2.shp")

river_buffer <- st_read("./data/shapefiles/aoi_affd_aff_py_s3_govn_pp_AOI500mBuffer.shp") 

river <- st_read("./data/shapefiles/Flood Extent Shape file/Flood extent_SHP.shp")

holding_centres <- st_read("./data/shapefiles/npl_shel_shl_pt_s3_various_pp_holding_centre.shp") 

# river <- st_read("./data/shapefiles/Flood Extent.gpkg", options = "CONVERT_TO_LINEAR=YES") 

```



## Damage and response data

```{r}

municipal_damage_losses <- read_csv("./data/municipal_damage_loss.csv")

municipal_long <- municipal_damage_losses |> 
  mutate(affected_hectares_agriculture = paddy_affected_hectares + vegetables_affected_hectares, 
         total_baseline_hectares = paddy_baseline_hectares + vegetables_baseline_hectares, 
         pc_affected_hectares = affected_hectares_agriculture / total_baseline_hectares, 
         pc_affected_buildings = affected_buildings / estimated_buildings_in_damaged_corridor, 
         pc_impacted_households = impacted_households / households_in_affected_wards_census_2021) |> 
  select(adm2_pcode, adm3_pcode, impacted_households, 
         pc_impacted_households, 
         impacted_population = impacted_population_total,
         affected_buildings, pc_affected_buildings,
         affected_hectares_agriculture, pc_affected_hectares) |> 
  pivot_longer(cols = impacted_households:pc_affected_hectares, 
               names_to = "variable", 
               values_to = "value") 

consolidated <- read_xlsx("./data/NEPAL 5W Data Consolidation 20260911.xlsx",
                          skip = 5,
                          sheet = "Compiled_Data") |> 
  janitor::clean_names() |> 
  mutate_at(c("province", "district", "municipality"), ~ str_to_title(.)) |> 
  mutate_at(c("province", "district", "municipality"), ~ str_trim(.)) |> 
  mutate(municipality = str_remove_all(municipality, " Gaunpalika")) |> 
  mutate(province = case_when(
    district == "Gorkha" ~ "Gandaki", 
    district == "Tanahu" ~ "Gandaki",
    TRUE ~ province
  )) |> 
  mutate(district = case_when(
    municipality == "Gosaikunda" ~ "Rasuwa", 
    municipality == "Bidur Municipality" ~ "Nuwakot", 
    TRUE ~ district
  )) |> 
  mutate(municipality = case_when(
    municipality == "Benighat" ~ "Benighat Rorang", 
    municipality == "Galchi Rural Municipality" ~ "Galchhi", 
    municipality == "Gandaki" ~ "Gandaki", 
    municipality == "Bheri Malika Municipality" ~ "Bheri Malika", 
    municipality == "Nalgad Municipality" ~ "Nalgad", 
    municipality == "Kathmandu Metropolitian City" ~ "Kathmandu", 
    municipality == "Nagarjun Municipality" ~ "Nagarjun", 
    municipality == "Belkotgadhi Municipality|Belkotgadhi Nagarpalika" ~ "Belkotgadhi", 
    str_detect(municipality, "Bidur") ~ "Bidur", 
    municipality == "Kispang Municipality" ~ "Kispang", 
    municipality == "Tarkeshwor" ~ "Tarakeshwor", 
    municipality == "Rasuwa Dao, Dhunche" ~ "Gosaikunda",
    str_detect(municipality, "Devghat") ~ "Devghat", 
    str_detect(municipality, "Gandaki") ~ "Gandaki", 
    str_detect(municipality, "Belkotgadhi") ~ "Belkotgadhi", 
    municipality == "Aanbukhaireni" ~ "Aanbu Khaireni",
    TRUE ~ municipality)) |> 
  left_join(
    nepal_admin |> 
      distinct(adm1_name, adm1_pcode), 
    by = c("province" = "adm1_name")
  ) |> 
  left_join(
    nepal_admin |> 
      distinct(adm1_pcode, adm2_name, adm2_pcode), 
    by = c("adm1_pcode", "district" = "adm2_name")
  ) |> 
  left_join(
    nepal_admin |> 
      distinct(adm1_pcode, adm2_pcode, 
             adm3_name, adm3_pcode), 
    by = c("adm1_pcode", "adm2_pcode", "municipality" = "adm3_name")
  ) |> 
  rename(individuals_reached = total_number_of_beneficiaries_reached_people_individuals) |> 
  filter(disaster_response_plan == "Rasuwa Flood Response") 

# census_individual <- read_csv("./data/nepal_census2021_ward_level_individual_tables_bagmati_gandaki_long.csv")

# Using this temporarily until the population figures are resolved
differences <- read_csv("./data/differences_between_flash_appeal_and_rdna_affected_wards.csv")

damage_points <- read_xlsx("./data/Consolidated Damage.xlsx") |> 
  clean_names() |> 
  rename(x = long, y = lat)
```


### Holding centre merge

```{r}

holding_centres_join <- holding_centres |> 
  st_transform(st_crs(adm3)) |> 
  st_join(
    adm3
  ) |> 
  filter(!is.na(name)) %>%
  filter(!st_is_empty(.)) %>%
  select(where(~ !all(is.na(.)))) |> 
  select(name, adm1_name, adm1_pcode, adm2_name, adm2_pcode, adm3_name, adm3_pcode, geometry) 

holding_centres_complete <- holding_centres_join |> 
  cbind(
    st_coordinates(holding_centres_join$geometry)
  ) |> 
  clean_names()

  st_coordinates(geometry)
  glimpse()
  
```

```{r}
damage_points_20260914 <- damage_points |> 
  rename(
    adm1_name = province, 
    adm2_name = district, 
    adm3_name = municipality
  ) |> 
  rbind(
    holding_centres_complete |> 
      st_drop_geometry() |> 
      mutate(type = "Holding Centre", 
             ownership = NA_character_,
             damage = NA_character_) |> 
      select(adm1_name, adm2_name, adm3_name, 
             name, type, x, y, ownership, damage)
  ) |> 
  mutate_at(vars(adm1_name, adm2_name, adm3_name), 
            ~ str_trim(.x)) |> 
  mutate(adm1_name = ifelse(adm1_name == "Bagamati", "Bagmati", adm1_name), 
         adm2_name = ifelse(adm2_name == "Chitwan", "Chitawan", adm2_name), 
         adm3_name = ifelse(adm3_name == "Ichchhakamana", "Ichchha Kamana", adm3_name)
         ) |> 
  left_join(
    nepal_admin |> 
      distinct(adm1_name, adm1_pcode, 
               adm2_name, adm2_pcode, 
               adm3_name, adm3_pcode), 
    by = c("adm1_name", "adm2_name", "adm3_name")
  ) 

damage_points_20260914 |> writexl::write_xlsx("./data/damage_points_20260914.xlsx")

```



# Plotting 

```{r logos}

combined_logos <- grid::rasterGrob(image_append(
  c(image_read("./plots/logos/UN Nepal-Logo_horizontal_match_size.png"),
    image_read("./plots/logos/002_COMM_GUID_iMMAPLogo2.png"))))

```


```{r}
HEX
"#002e6e"
"#004987"
"#0074b7"
"#009edb" -- UN blue
"#64bdea"
"#c5dfef"
"#e3edf6"

"#003425"
"#004d35"
"#006747"
"#338c46"
"#72bf44"
"#cee3a0"
"#e6efd0"

```

## Magnitude and severity mapping 

```{r plotting-functions}
magnitude_plot <- function(tbl, filter_value) {
  
  tbl |> 
    filter(variable == filter_value) |> 
    mutate(variable = str_replace_all(variable, "_", " "),
           variable = str_to_title(variable)) |> 
    mutate(value = ifelse(value == 0, NA_integer_, value)) |> 
    right_join(adm3, 
              by = c("adm2_pcode", "adm3_pcode")) |>
    mutate(adm3_name_label = ifelse(!is.na(value), adm3_name, ""),
           label = ifelse(!is.na(value),
                          as.character(format(round(value, 1), big.mark = ",")), 
                          "")) |>
    replace_na(list(label = "", adm3_name_label = "")) |> 
    st_as_sf() |> 
    ggplot() +
    geom_sf(aes(fill = value), linewidth = .1) +
    geom_sf(data = river, colour = "#e56a54", fill = "#e56a54", alpha = .2) +
    geom_shadowtext(
      aes(x = center_lon, y = center_lat, 
          label = paste0(adm3_name_label, "\n", label)), 
      size = 2, color = "black",  bg.color = "white", bg.r = 0.1) +
    coord_sf(xlim = c(84.3, 85.8), ylim = c(27.63, 28.4), expand = TRUE) +
    scale_fill_gradient(low = "#e3edf6", high = "#002e6e", labels = comma, na.value = "grey97") +
    labs(title = paste0(str_to_title(str_replace_all(filter_value, "_", " "))), 
         fill = paste0(str_to_title(str_replace_all(filter_value, "_", "\n"))), 
         x = "", y = "") +
    theme(plot.subtitle = element_text(margin = margin(b = -2)))

}


severity_plot <- function(tbl, filter_value) {
  
  tbl |> 
    filter(variable == filter_value) |> 
    mutate(value = ifelse(value == 0, NA_integer_, value)) |> 
    right_join(adm3, 
              by = c("adm2_pcode", "adm3_pcode")) |>
    mutate(adm3_name_label = ifelse(!is.na(value), adm3_name, ""),
           label = ifelse(!is.na(value),
                          paste0(round(value * 100, 2), "%"),  
                          "")) |>
    replace_na(list(label = "", adm3_name_label = "")) |> 
    st_as_sf() |> 
    ggplot() +
    geom_sf(aes(fill = value), linewidth = .1) +
    geom_sf(data = river, colour = "#e56a54", fill = "#e56a54", alpha = .2) +
    geom_shadowtext(
      aes(x = center_lon, y = center_lat, 
          label = paste0(adm3_name_label, "\n", label)), 
      size = 2, color = "black",  bg.color = "white", bg.r = 0.1) +
    coord_sf(xlim = c(84.3, 85.8), ylim = c(27.63, 28.4), expand = TRUE) + 
    scale_fill_gradient(low = "#e3edf6", high = "#002e6e", labels = percent, na.value = "grey97")+
    labs(x = "", y = "") + 
    theme(plot.subtitle = element_text(margin = margin(b = -2)))

}
```



```{r magnitude-plots-assembly, fig.height=9}

municipal_long |> 
  magnitude_plot("impacted_population") +
  labs(title = "The Population was Impacted across 61 wards in 20 municipalities", 
       subtitle = "As of 20260909, from the NDRRMA Rapid Disaster Needs Assessment.") +

municipal_long |> 
  magnitude_plot("affected_buildings") + 
  labs(subtitle = "As of 20260909, from the NDRRMA Rapid Disaster Needs Assessment.", 
       title = "7,570 buildings were Impacted across the Damage Corridor") +
  
municipal_long |> 
  magnitude_plot("affected_hectares_agriculture") + 
  labs(subtitle = "As of 20260909, from the NDRRMA Rapid Disaster Needs Assessment.", 
       title = "1,806 Hectares of Agricultural Land were Impacted") +

consolidated |>
  filter(municipality != "Kathmandu") |> 
  filter(disaster_response_plan == "Rasuwa Flood Response") |> 
  filter(response_modality != "Awareness/Advocacy") |> 
  filter(is.finite(individuals_reached)) |> 
  filter(!is.na(adm2_pcode) & !is.na(adm3_pcode)) |> 
  group_by(adm2_pcode, adm3_pcode) |> 
  summarise(individuals_reached = max(individuals_reached, na.rm = TRUE), 
            .groups = "drop") |> 
  mutate(variable = "individuals_reached") |> 
  rename(value = individuals_reached) |> 
  magnitude_plot("individuals_reached") +
  labs(subtitle = "As of 20260911.", 
       title = "Individuals Reached by the Humanitarian Response according to the 5Ws") +
  
  combined_logos +

  plot_layout(ncol = 2, 
              heights = c(10, 10, 1), 
  design = "
AAABBB
CCCDDD
EE####
") + 
  plot_annotation(
    title = "Municipal-level plots of the Magnitude of the Rasuwa Floods Disaster Impacts and the Humanitarian Response", 
    caption = "Sources: Survey Department, Government of Nepal; Nepal National Disaster Risk Reduction and Management Authority; UNOSAT; United Nations Nepal and its humanitarian partners.", 
    theme = theme(
      plot.title = element_text(size = 20, face = 'bold'))
    )

ggsave("./plots/magnitude_disaster_impact_5ws.png", height = 11.7, width = 16.5, units = "in")
```


```{r severity-plots-assembly, fig.height=9}

municipal_damage_losses |> 
  left_join(
    differences |>
      filter(rdna_affected == 1) |>
      group_by(adm2_pcode, adm3_pcode) |>
      summarise(population_in_affected_wards = sum(projection_2026_population_total, na.rm = TRUE),
                .groups = "drop"), 
    by = c("adm2_pcode", "adm3_pcode")) |> 
  mutate(pc_affected_population = impacted_population_total / population_in_affected_wards) |> 
  select(district, adm2_pcode, municipality, adm3_pcode, value = pc_affected_population) |>
  mutate(variable = "% of Population Affected") |> 
  severity_plot("% of Population Affected") + 
  labs(title = "% of Population Impacted, within Damage Corridor", 
       subtitle = "As of 20260909, from the NDRRMA Rapid Disaster Needs Assessment.", 
       fill = "% of\nPopulation\nAffected") +

municipal_long |> 
  mutate(variable = case_when(
    variable == "pc_affected_buildings" ~ "% of buildings affected, within damage corridor", 
    variable == "pc_affected_hectares" ~ "% of hectares of agricultural land, within damage corridor", 
    TRUE ~ variable
  )) |> 
  severity_plot("% of buildings affected, within damage corridor") + 
  labs(title = "% of Buildings Affected, within Damage Corridor", 
       subtitle = "As of 20260909, from the NDRRMA Rapid Disaster Needs Assessment.",
       fill = "% of\nBuildings\nAffected") +

municipal_long |> 
  mutate(variable = case_when(
    variable == "pc_affected_buildings" ~ "% of buildings affected, within damage corridor", 
    variable == "pc_affected_hectares" ~ "% of hectares of agricultural land, within damage corridor", 
    TRUE ~ variable
  )) |> 
  severity_plot("% of hectares of agricultural land, within damage corridor") + 
  labs(title = "% of Agricultural land affected, within Damage Corridor", 
       subtitle = "As of 20260909, from the NDRRMA Rapid Disaster Needs Assessment.",
       fill = "% of\nAgricultrual\nland\nAffected") +

consolidated |>
  filter(municipality != "Kathmandu") |> 
  filter(disaster_response_plan == "Rasuwa Flood Response") |> 
  filter(response_modality != "Awareness/Advocacy") |> 
  filter(is.finite(individuals_reached)) |> 
  filter(!is.na(adm2_pcode) & !is.na(adm3_pcode)) |> 
  group_by(adm2_pcode, adm3_pcode) |> 
  summarise(individuals_reached = max(individuals_reached, na.rm = TRUE), 
            .groups = "drop") |> 
  right_join(
    differences |> 
      filter(rdna_affected == 1) |> 
      group_by(adm2_pcode, adm3_pcode) |> 
      summarise(population = sum(projection_2026_population_total), 
                .groups = "drop"), 
    by = c("adm2_pcode", "adm3_pcode")
  ) |> 
  mutate(pc_of_affected_reached = individuals_reached / population, 
         variable = "% of Affected Population Reached by 5W activities") |>
  select(adm2_pcode, adm3_pcode, variable, value = pc_of_affected_reached) |> 
  severity_plot("% of Affected Population Reached by 5W activities") + 
  labs(title = "% of Affected Population Reached by 5W activities", 
       fill = "% of\nPopulation\nReached", 
       subtitle = "As a percentage of the population of affected wards, as of 20260911.") +
  
  combined_logos +

  plot_layout(ncol = 2, 
              heights = c(10, 10, 1), 
  design = "
AAABBB
CCCDDD
EE####
") + 
  plot_annotation(
    title = "Municipal-level plots of the Severity of the Rasuwa Floods Disaster Impacts and the Humanitarian Response", 
    caption = "Sources: Survey Department, Government of Nepal; Nepal National Disaster Risk Reduction and Management Authority; UNOSAT; United Nations Nepal and its humanitarian partners.", 
    theme = theme(
      plot.title = element_text(size = 20, face = 'bold'))
  )

ggsave("./plots/severity_disaster_impact_5ws.png", height = 11.7, width = 16.5, units = "in")
```


```{r}
consolidated |>
  filter(municipality != "Kathmandu") |> 
  filter(is.finite(individuals_reached)) |> 
  filter(!is.na(adm2_pcode) & !is.na(adm3_pcode)) |> 
  group_by(adm2_pcode, adm3_pcode) |> 
  summarise(individuals_reached = max(individuals_reached, na.rm = TRUE), 
            .groups = "drop") |> 
  right_join(
    differences |> 
      filter(rdna_affected == 1) |> 
      group_by(adm2_pcode, adm3_pcode) |> 
      summarise(population = sum(projection_2026_population_total), 
                .groups = "drop"), 
    by = c("adm2_pcode", "adm3_pcode")
  ) |> 
  mutate(pc_of_affected_reached = individuals_reached / population, 
         variable = "% of Affected Population Reached by 5W activities") |>
  select(adm2_pcode, adm3_pcode, variable, value = pc_of_affected_reached)
```



## Wards

### Ward differences 

```{r}
differences |> 
  mutate(
    assessment_category = case_when(
      flash_appeal_affected == 1 & rdna_affected == 1 ~ "Both", 
      flash_appeal_affected == 1 & rdna_affected == 0 ~ "Only Flash Appeal", 
      rdna_affected == 1 & flash_appeal_affected == 0 ~ "Only RDNA", 
      TRUE ~ NA_character_
    )
  ) |> 
  right_join(wards, 
             by = c("adm2_pcode", "adm3_pcode", "ward")) |> 
  st_as_sf() |> 
  mutate(ward_label = ifelse(!is.na(flash_appeal_affected == 1 | rdna_affected ==1), 
                             paste0(ward, "\n", format(projection_2026_population_total, big.mark = ",")), 
                             ""), 
         adm3_label = ifelse(adm3_pcode %in% (differences |> distinct(adm3_pcode) |> pull()), 
                             municipality, 
                             "")) |> 
  ggplot() +
  geom_sf(linewidth = .1, alpha = .1, fill = "grey97") +
  geom_sf(data = adm3, alpha = .25, linewidth = .5, colour = "grey70", fill = NA) +
  geom_sf_text(data = adm3 |> 
            mutate(adm3_label = ifelse(adm3_pcode %in% (differences |> distinct(adm3_pcode) |> pull()),
                                       adm3_name,
                                       "")), 
            aes(label = adm3_label)
          ) + 
  geom_sf(aes(fill = assessment_category), alpha = .7, colour = NA) + 
  scale_fill_manual(values = c(
    "Both" = "#0074b7", 
    "Only Flash Appeal" = "#c5dfef", 
    "Only RDNA" = "#338c46"), 
    na.value = "grey97", 
    na.translate = FALSE) +
  geom_sf(data = river, colour = "#e56a54", fill = "#e56a54", alpha = .5) +
  geom_shadowtext(
      aes(label = ward_label, 
          geometry = geometry), 
      stat = "sf_coordinates",
      size = 2, color = "black",  bg.color = "white", bg.r = 0.1) +
    coord_sf(xlim = c(84.4, 85.6), ylim = c(27.63, 28.4), expand = TRUE) + 
  labs( x = "", y = "", 
       fill = "") +
  
  combined_logos +

  plot_layout(ncol = 1, 
              heights = c(25, 1), 
  design = "
AAAAAA
BB####
") + 
  plot_annotation(
    title = "Affected wards and their populations, mentioned in the Flash Appeal and the Rapid Disaster Needs Assessment", 
    subtitle = "Ward numbers and their 2026 population projections are labelled. Flood Extent.", 
    caption = "Sources: Nepal National Disaster Risk Reduction and Management Authority; UNOSAT; United Nations Nepal and its humanitarian partners.", 
    theme = theme(
      plot.title = element_text(size = 20, face = 'bold'))
  )

ggsave("./plots/affected_wards.png", height = 11.7, width = 16.5, units = "in")  
```



### Wards and points


```{r}
differences |> 
  mutate(
    rdna_affected = ifelse(rdna_affected == 1, "Affected", NA_character_)) |> 
  right_join(wards, 
             by = c("adm2_pcode", "adm3_pcode", "ward")) |> 
  st_as_sf() |> 
  mutate(ward_label = ifelse(!is.na(rdna_affected == "Affected"), 
                             paste0(ward, "\n", format(projection_2026_population_total, big.mark = ",")), 
                             ""), 
         adm3_label = ifelse(adm3_pcode %in% (differences |> distinct(adm3_pcode) |> pull()), 
                             municipality, 
                             "")) |> 
  ggplot() +
  # Ward boundaries
  geom_sf(linewidth = .1, alpha = .1, fill = "grey97") +
  # Municipality boundaries
  geom_sf(data = adm3, alpha = .25, linewidth = .5, colour = "grey70", fill = NA) +
  # Municipality names
  geom_sf_text(data = adm3 |> 
            mutate(adm3_label = ifelse(adm3_pcode %in% (differences |> distinct(adm3_pcode) |> pull()),
                                       adm3_name,
                                       "")), 
            aes(label = adm3_label)
          ) + 
  # Affected wards 
  geom_sf(aes(fill = rdna_affected), alpha = .7, colour = NA) +
  scale_fill_manual(values = c("Affected" = "#c5dfef"), 
    na.value = "grey97", 
    na.translate = FALSE) +
  geom_sf(data = river, colour = "#002e6e", fill = "#002e6e", alpha = .5) +
  # Damage points 
  geom_point(data = damage_points, 
             aes(x = x, y = y, colour = type)) +
  geom_label_repel(data = damage_points, 
                aes(x = x, y = y, label = name),
                size = 1.5) +
  # geom_shadowtext(data = damage_points, 
  #                 aes(label = name, x = x, y = y),
  #     size = 2, color = "black",  bg.color = "white", bg.r = 0.1) +
  scale_colour_manual(values = 
                        c("Hydropower" = "#ffc800", 
                          "Medical Facility" = "#e56a54", 
                          "School" = "#72bf44")
  ) +
  coord_sf(xlim = c(84.4, 85.6), ylim = c(27.63, 28.4), expand = TRUE) + 
  labs( x = "", y = "", 
       fill = "") +
  
  combined_logos +

  plot_layout(ncol = 1, 
              heights = c(25, 1), 
  design = "
AAAAAA
BB####
") + 
  plot_annotation(
    title = "Affected wards and Key Infrastructure Affected", 
    caption = "Sources: Nepal National Disaster Risk Reduction and Management Authority; UNOSAT; United Nations Nepal and its humanitarian partners.", 
    theme = theme(
      plot.title = element_text(size = 20, face = 'bold'))
  )

ggsave("./plots/affected_wards_infrastructure.png", height = 11.7, width = 16.5, units = "in")  

```



## Humanitarian snapshot map

```{r}
municipal_damage_losses |> 
  count(district)
```


```{r}

impacted_buildings <- municipal_damage_losses |> 
  select(district:adm3_pcode, 
         impacted_buildings) |> 
  filter(!is.na(impacted_buildings)) |> 
  left_join(
    adm3, 
    by = c("adm2_pcode", "adm3_pcode")
  ) |> 
  select(adm3_name, adm3_pcode, x = center_lon, y = center_lat, impacted_buildings)

floods_bbox_sf <- st_bbox(c(xmin = 84.3, xmax = 85.8, ymin = 27.5, ymax = 29), 
                       crs = st_crs(4326)) |> 
  st_as_sfc()

floods_topo <- get_tiles(floods_bbox_sf, provider = "Esri.WorldShadedRelief", zoom = 11)

impacted_buildings_map <- impacted_buildings |>
  ggplot() + 
  geom_spatraster_rgb(data = floods_topo, alpha = .2) + 
  # Municipality boundaries
  geom_sf(data = adm3 |> 
            filter(adm2_name %in% c("Chitawan", "Dhading", "Gorkha", "Nuwakot", 
                                    "Rasuwa", "Tanahu")),
                   alpha = .25, linewidth = .5, colour = "grey70", fill = NA) +
  # Municipality names
  geom_sf_text(data = adm3 |> 
            mutate(adm3_label = ifelse(adm3_pcode %in% (impacted_buildings |> distinct(adm3_pcode) |> pull()),
                                       adm3_name,
                                       "")), 
            aes(label = adm3_label), 
            colour = "grey20", 
            alpha = .5, 
            size = 4, 
            nudge_x = -0.03, nudge_y = -0.02
          ) + 
  geom_sf(data = river, colour = "#002e6e", fill = "#002e6e", alpha = .6) +
  geom_point(
    aes(x = x, y = y, size = impacted_buildings), 
    colour = "#e56a54", 
    alpha = .7
  ) + 
  scale_size_continuous(range = c(1, 10), labels = comma) +
  coord_sf(xlim = c(84.4, 85.6), ylim = c(27.63, 28.4), 
           expand = FALSE,
           datum = st_crs(floods_bbox_sf)) +
  theme_void() + 
  labs(size = "Impacted\nbuildings", 
       title = "NEPAL | Buildings Impacted by the Rasuwa-Trishuli Floods") +
  guides(size = guide_legend(override.aes = list(alpha = .7))) + 
  theme(legend.position = c(0.92, 0.17), 
        plot.title = element_text(face = "bold"))

```

```{r}
minimap <- adm3 |> 
  st_transform(st_crs(4326)) |> 
  ggplot() + 
  geom_sf(color = NA) + 
  geom_rect(aes(xmin = 84.4, xmax = 85.6, ymin = 27.63, ymax = 28.35), 
            color = "#ed1847", 
            fill = NA,      # Keeps the inside transparent
            linewidth = .7) + 
  theme_void() + 
  theme(
    panel.border = element_rect(fill = NA, color = "black", linewidth = 1),
    plot.background = element_rect(fill = "white", color = NA)
  )
```



```{r}
combined_map <- ggdraw() +
  draw_plot(impacted_buildings_map) +  # Main map fills the whole canvas by default
  draw_plot(minimap, 
    x = 0.05,    # Distance from left border (0 to 1)
    y = 0.65,    # Distance from bottom border (0 to 1)
    width = 0.3,  # Relative width of the minimap (30% of canvas)
    height = 0.3  # Relative height of the minimap (30% of canvas)
  ) + 
  canvas(8, 6)

save_ggplot(combined_map, "./plots/snapshot_map.png")
```





  