---
title: "Untitled"
format: html
---

```{r setup}

knitr::opts_chunk$set(echo = FALSE, fig.width=9, message = FALSE, warning=FALSE)

library(tidyverse)
library(sf)
library(readxl)
library(kableExtra)
library(flextable)
library(viridis)
library(scales)

`%out%` <- Negate(`%in%`)

theme_set(theme_light())
```
# Geodata

```{r}
bagmati <- st_read("./data/shapefiles/Ward_Bagmati.shp") |> 
  st_drop_geometry()

gandaki <- st_read("./data/shapefiles/Ward_Gandaki.shp") |> 
  st_drop_geometry()

nepal_admin <- read_xlsx("./data/npl_admin_boundaries.xlsx", 
                         sheet = 7) |> 
  select(adm3_name, adm3_pcode, adm2_name, adm2_pcode, adm1_name, adm1_pcode)

wards <- st_read("./data/npl_admn_ad4_py_s1_ocha_hp_wards.shp")

affected_wards <- read_xls("./data/Affected_wardsV2.xls") |> 
  janitor::clean_names()

adm3 <- st_read("./raw_data/npl_admin_boundaries.shp/npl_admin3.shp")
``` 


# Wards

```{r}
affected_wards_population <- read_xlsx("./data/Copy of Affected Palikas and Wards_ward_wise_population_projection 2026 (1).xlsx") |> 
  janitor::clean_names()
```


## Census

### Functions


```{r}
ward_fill_filter <- function(tbl) {
  tbl |> 
    fill(province, .direction = "down") |>
    fill(district, .direction = "down") |>
    fill(municipality, .direction = "down") |>
    filter(!is.na(ward))
}

ward_fill_filter2 <- function(tbl) {
  tbl |> 
    fill(province, .direction = "down") |>
    fill(district, .direction = "down") |>
    fill(municipality, .direction = "down") |>
    fill(ward, .direction = "down") |> 
    filter(!is.na(ward))
}

bagmati_district_names <- function(tbl) {
  tbl |>
    mutate(province = "Bagmati") |> 
    mutate(district = as.character(district)) |>
    mutate(
      district = case_when(
        district == 23 ~ "Dolakha",
        district == 24 ~ "Sindhupalchok",
        district == 25 ~ "Rasuwa",
        district == 26 ~ "Dhading",
        district == 27 ~ "Nuwakot",
        district == 28 ~ "Kathmandu",
        district == 29 ~ "Bhaktapur",
        district == 30 ~ "Lalitpur",
        district == 31 ~ "Kavrepalanchok",
        district == 32 ~ "Ramechhap",
        district == 33 ~ "Sindhuli",
        district == 34 ~ "Makwanpur",
        district == 35 ~ "Chitawan",
        TRUE ~ district
      )
    ) |> 
    filter(name %out% c("Dolakha", "Sindhupalchok", "Rasuwa", "Dhading", 
                      "Nuwakot", "Kathmandu", "Bhaktapur", "Lalitpur",
                      "Kavrepalanchok", "Ramechhap", "Sindhuli", "Makwanpur", 
                      "Chitawan", "NEPAL", "BAGMATI")) |> 
  select(-municipality) |> 
  rename(municipality = name) |> 
  mutate(ward = ifelse(ward == "Total", "All Wards", ward))
}

gandaki_district_names <- function(tbl) {
  tbl |>
    mutate(province = "Gandaki") |>
    mutate(district = as.character(district)) |>
    mutate(
      district = case_when(
        district == 36 ~ "Gorkha",
        district == 37 ~ "Manang",
        district == 38 ~ "Mustang",
        district == 39 ~ "Myagdi",
        district == 40 ~ "Kaski",
        district == 41 ~ "Lamjung",
        district == 42 ~ "Tanahu",
        district == 43 ~ "Nawalparasi East",
        district == 44 ~ "Syangja",
        district == 45 ~ "Parbat",
        district == 46 ~ "Baglung",
        TRUE ~ district
      )
    ) |> 
    filter(name %out% c("Gorkha", "Manang", "Mustang", "Myagdi", "Kaski",
                      "Lamjung", "Tanahu", "Nawalparasi East", "Syangja", "Parbat",
                      "Baglung", "NEPAL", "GANDAKI")) |> 
  select(-municipality) |> 
  rename(municipality = name) |> 
  mutate(ward = ifelse(ward == "Total", "All Wards", ward))
}
```

### Household - Bagmati 

```{r bagmati warning=FALSE, message=FALSE}
bagmati <- cbind(
  read_xlsx("./data/census/WRD_Bagmati_Hhld01-OwnershipOfHouse.xlsx", 
          skip = 3) |>
  setNames(c("province", "district", "municipality", "ward", "ownership_total", 
             "ownership_owned", 
             "ownership_rented", 
             "ownership_institutional", 
             "ownership_other")) |> 
  ward_fill_filter(), 
  
  read_xlsx("./data/census/WRD_Bagmati_Hhld02-FoundationOfHouse.xlsx", 
          skip = 2) |> 
  setNames(c("province", "district", "municipality", "ward", "foundation_total", 
             "foundation_mud", 
             "foundation_mud_bonded_bricks_stone", 
             "foundation_cement_bonded_bricks_stone", 
             "foundation_reinforced_cement_concrete_with_pillars", 
             "foundation_wooden_pillars", 
             "foundation_other")) |> 
  ward_fill_filter() |> 
  select(-province, -district, -municipality, -ward), 
  
  read_xlsx("./data/census/WRD_Bagmati_Hhld03-OuterWallOfHouse.xlsx", 
          skip = 2) |> 
  setNames(c("province", "district", "municipality", "ward", "outer_wall_total",
             "outer_wall_mud_bonded_bricks_stone", 
             "outer_wall_cement_bonded_bricks_stone", 
             "outer_wall_wood_planks", 
             "outer_wall_bamboo", 
             "outer_wall_unbaked_bricks", 
             "outer_wall_galvanised_sheet", 
             "outer_wall_prefabricated_sheet", 
             "outer_wall_other")) |> 
  ward_fill_filter() |> 
  select(-province, -district, -municipality, -ward), 
  
  read_xlsx("./data/census/WRD_Bagmati_Hhld04-RoofOfHouse.xlsx", skip = 2) |> 
  setNames(c("province", "district", "municipality", "ward", "roof_total",
             "roof_galvanised_sheet", 
             "roof_reinforced_cement_concrete", 
             "roof_thatch_straw", 
             "roof_tile", 
             "roof_stone_slate", 
             "roof_wood_planks", 
             "roof_mud", 
             "roof_other")) |> 
  ward_fill_filter() |> 
  select(-province, -district, -municipality, -ward), 
  
  read_xlsx("./data/census/WRD_Bagmati_Hhld05-FloorOfHouse.xlsx", 
          skip = 2) |> 
  setNames(c("province", "district", "municipality", "ward", "floor_total",
             "floor_mud", 
             "floor_wooden_plank_bamboo", 
             "floor_bricks_stone", 
             "floor_ceramic_tile", 
             "floor_cemented", 
             "floor_other")) |>
  ward_fill_filter() |> 
  select(-province, -district, -municipality, -ward), 
  
  read_xlsx("./data/census/WRD_Bagmati_Hhld06-SourceOfDrinkingWater.xlsx", skip = 2) |> 
  setNames(c("province", "district", "municipality", "ward", "drinking_water_total",
           "drinking_water_tap_piped_within_premises", 
           "drinking_water_tap_piped_outside_premises", 
           "drinking_water_tubewell_handpump", 
           "drinking_water_covered_well_kuwa", 
           "drinking_water_uncovered_well_kuwa", 
           "drinking_water_spout_water", 
           "drinking_water_river_stream", 
           "drinking_water_jar_bottle", 
           "drinking_water_other")) |> 
  ward_fill_filter() |> 
  select(-province, -district, -municipality, -ward), 
  
  read_xlsx("./data/census/WRD_Bagmati_Hhld07-CookingFuel.xlsx", skip = 2) |> 
  setNames(c("province", "district", "municipality", "ward", "cooking_fuel_total",
             "cooking_fuel_wood_firewood", 
             "cooking_fuel_lpg", 
             "cooking_fuel_electricity", 
             "cooking_fuel_cowdung", 
             "cooking_fuel_biogas", 
             "cooking_fuel_kerosene", 
             "cooking_fuel_other")) |> 
  ward_fill_filter() |> 
  select(-province, -district, -municipality, -ward),
  
  read_xlsx("./data/census/WRD_Bagmati_Hhld08-LightingFuel.xlsx", skip = 2) |> 
  setNames(c("province", "district", "municipality", "ward", "lighting_fuel_total",
             "lighting_electricity", 
             "lighting_solar", 
             "lighting_kerosene", 
             "lighting_biogas", 
             "lighting_other")) |> 
  ward_fill_filter() |> 
  select(-province, -district, -municipality, -ward),
  
  read_xlsx("./data/census/WRD_Bagmati_Hhld09-ToiletFacility.xlsx", skip = 2) |> 
  setNames(c("province", "district", "municipality", "ward", "toilet_total",
             "toilet_flush_public_sewerage", 
             "toilet_flush_septic_tank", 
             "toilet_pit", 
             "toilet_public", 
             "toilet_no_toilet")) |> 
  ward_fill_filter() |> 
  select(-province, -district, -municipality, -ward),
  
  read_xlsx("./data/census/WRD_Bagmati_Hhld10-HouseholdAmenities.xlsx", skip = 2) |> 
  setNames(c("province", "district", "municipality", "ward", "hh_amenities_total",
             "hh_amenities_without", 
             "hh_amenities_at_least_one", 
             "hh_amenities_radio", 
             "hh_amenities_television", 
             "hh_amenities_landline", 
             "hh_amenities_mobile_phone_ordinary", 
             "hh_amenities_mobile_phone_smart", 
             "hh_amenities_computer_laptop", 
             "hh_amenities_internet",
             "hh_amenities_car_jeep_van", 
             "hh_amenities_motorcycle_scooter", 
             "hh_amenities_bicycle", 
             "hh_amenities_electric_fan", 
             "hh_amenities_refridgerator", 
             "hh_amenities_washing_machine", 
             "hh_amenities_air_conditioner")) |> 
  ward_fill_filter() |> 
  select(-province, -district, -municipality, -ward),
  
  read_xlsx("./data/census/Rev_Bagmati_Hhld_WealthQuintileHousehold_Ward_formated.xlsx", skip = 2) |> 
  setNames(c("province", "district", "municipality", "name", "ward", "wealth_quintile_total",
             "wealth_quintile_poorest_quintile_count", 
             "wealth_quintile_poorer_quintile_count", 
             "wealth_quintile_middle_quintile_count", 
             "wealth_quintile_richer_quintile_count", 
             "wealth_quintile_richest_quintile_count", 
             "wealth_quintile_poorest_quintile_pc", 
             "wealth_quintile_poorer_quintile_pc",
             "wealth_quintile_middle_quintile_pc", 
             "wealth_quintile_richer_quintile_pc", 
             "wealth_quintile_richest_quintile_pc")) |> 
  bagmati_district_names() |> 
  select(-province, -district, -municipality, -ward), 
  
  read_xlsx("./data/census/Rev_Bagmati_Hhld_QualityOfHouse_Ward_formated.xlsx", skip = 2) |> 
   setNames(c("province", "district", "municipality", "name", "ward", "house_quality_total",
             "house_quality_most_adequate_count", 
             "house_quality_adequate_count", 
             "house_quality_moderate_count", 
             "house_quality_inadequate_count", 
             "house_quality_least_adequate_count", 
             "house_quality_most_adequate_pc", 
             "house_quality_adequate_pc",
             "house_quality_moderate_pc", 
             "house_quality_inadequate_pc", 
             "house_quality_least_adequate_pc")) |> 
 bagmati_district_names() |>  
 select(-province, -district, -municipality, -ward) 
)
```

### Household - Gandaki

```{r}
gandaki <- cbind(
  read_xlsx("./data/census/WRD_Gandaki_Hhld01-OwnershipOfHouse.xlsx", 
          skip = 3) |>
  setNames(c("province", "district", "municipality", "ward", "ownership_total", 
             "ownership_owned", 
             "ownership_rented", 
             "ownership_institutional", 
             "ownership_other")) |> 
  ward_fill_filter(), 
  
  read_xlsx("./data/census/WRD_Gandaki_Hhld02-FoundationOfHouse.xlsx", 
          skip = 2) |> 
  setNames(c("province", "district", "municipality", "ward", "foundation_total", 
             "foundation_mud", 
             "foundation_mud_bonded_bricks_stone", 
             "foundation_cement_bonded_bricks_stone", 
             "foundation_reinforced_cement_concrete_with_pillars", 
             "foundation_wooden_pillars", 
             "foundation_other")) |> 
  ward_fill_filter() |> 
  select(-province, -district, -municipality, -ward) , 
  
  read_xlsx("./data/census/WRD_Gandaki_Hhld03-OuterWallOfHouse.xlsx", 
          skip = 2) |> 
  setNames(c("province", "district", "municipality", "ward", "outer_wall_total",
             "outer_wall_mud_bonded_bricks_stone", 
             "outer_wall_cement_bonded_bricks_stone", 
             "outer_wall_wood_planks", 
             "outer_wall_bamboo", 
             "outer_wall_unbaked_bricks", 
             "outer_wall_galvanised_sheet", 
             "outer_wall_prefabricated_sheet", 
             "outer_wall_other")) |> 
  ward_fill_filter() |> 
  select(-province, -district, -municipality, -ward), 
  
  read_xlsx("./data/census/WRD_Gandaki_Hhld04-RoofOfHouse.xlsx", skip = 2) |> 
  setNames(c("province", "district", "municipality", "ward", "roof_total",
             "roof_galvanised_sheet", 
             "roof_reinforced_cement_concrete", 
             "roof_thatch_straw", 
             "roof_tile", 
             "roof_stone_slate", 
             "roof_wood_planks", 
             "roof_mud", 
             "roof_other")) |> 
  ward_fill_filter() |> 
  select(-province, -district, -municipality, -ward), 
  
  read_xlsx("./data/census/WRD_Gandaki_Hhld05-FloorOfHouse.xlsx", 
          skip = 2) |> 
  setNames(c("province", "district", "municipality", "ward", "floor_total",
             "floor_mud", 
             "floor_wooden_plank_bamboo", 
             "floor_bricks_stone", 
             "floor_ceramic_tile", 
             "floor_cemented", 
             "floor_other")) |>
  ward_fill_filter() |> 
  select(-province, -district, -municipality, -ward) , 
  
  read_xlsx("./data/census/WRD_Gandaki_Hhld06-SourceOfDrinkingWater.xlsx", skip = 2) |> 
  setNames(c("province", "district", "municipality", "ward", "drinking_water_total",
           "drinking_water_tap_piped_within_premises", 
           "drinking_water_tap_piped_outside_premises", 
           "drinking_water_tubewell_handpump", 
           "drinking_water_covered_well_kuwa", 
           "drinking_water_uncovered_well_kuwa", 
           "drinking_water_spout_water", 
           "drinking_water_river_stream", 
           "drinking_water_jar_bottle", 
           "drinking_water_other")) |> 
  ward_fill_filter() |> 
  select(-province, -district, -municipality, -ward) , 
  
  read_xlsx("./data/census/WRD_Gandaki_Hhld07-CookingFuel.xlsx", skip = 2) |> 
  setNames(c("province", "district", "municipality", "ward", "cooking_fuel_total",
             "cooking_fuel_wood_firewood", 
             "cooking_fuel_lpg", 
             "cooking_fuel_electricity", 
             "cooking_fuel_cowdung", 
             "cooking_fuel_biogas", 
             "cooking_fuel_kerosene", 
             "cooking_fuel_other")) |> 
  ward_fill_filter() |> 
  select(-province, -district, -municipality, -ward), 
  
  read_xlsx("./data/census/WRD_Gandaki_Hhld08-LightingFuel.xlsx", skip = 2) |> 
  setNames(c("province", "district", "municipality", "ward", "lighting_fuel_total",
             "lighting_electricity", 
             "lighting_solar", 
             "lighting_kerosene", 
             "lighting_biogas", 
             "lighting_other")) |> 
  ward_fill_filter() |> 
  select(-province, -district, -municipality, -ward), 
  
  read_xlsx("./data/census/WRD_Gandaki_Hhld09-ToiletFacility.xlsx", skip = 2) |> 
  setNames(c("province", "district", "municipality", "ward", "toilet_total",
             "toilet_flush_public_sewerage", 
             "toilet_flush_septic_tank", 
             "toilet_pit", 
             "toilet_public", 
             "toilet_no_toilet")) |> 
  ward_fill_filter() |> 
  select(-province, -district, -municipality, -ward), 
  
  read_xlsx("./data/census/WRD_Gandaki_Hhld10-HouseholdAmenities.xlsx", skip = 2) |> 
  setNames(c("province", "district", "municipality", "ward", "hh_amenities_total",
             "hh_amenities_without", 
             "hh_amenities_at_least_one", 
             "hh_amenities_radio", 
             "hh_amenities_television", 
             "hh_amenities_landline", 
             "hh_amenities_mobile_phone_ordinary", 
             "hh_amenities_mobile_phone_smart", 
             "hh_amenities_computer_laptop", 
             "hh_amenities_internet",
             "hh_amenities_car_jeep_van", 
             "hh_amenities_motorcycle_scooter", 
             "hh_amenities_bicycle", 
             "hh_amenities_electric_fan", 
             "hh_amenities_refridgerator", 
             "hh_amenities_washing_machine", 
             "hh_amenities_air_conditioner")) |> 
  ward_fill_filter() |> 
  select(-province, -district, -municipality, -ward), 
  
  read_xlsx("./data/census/Rev_Gandaki_Hhld_WealthQuintileHousehold_Ward_formated.xlsx", skip = 2) |> 
  setNames(c("province", "district", "municipality", "name", "ward", "wealth_quintile_total",
             "wealth_quintile_poorest_quintile_count", 
             "wealth_quintile_poorer_quintile_count", 
             "wealth_quintile_middle_quintile_count", 
             "wealth_quintile_richer_quintile_count", 
             "wealth_quintile_richest_quintile_count", 
             "wealth_quintile_poorest_quintile_pc", 
             "wealth_quintile_poorer_quintile_pc",
             "wealth_quintile_middle_quintile_pc", 
             "wealth_quintile_richer_quintile_pc", 
             "wealth_quintile_richest_quintile_pc")) |> 
  gandaki_district_names() |> 
  # One extra municipality (electoral constituency, really)
  # That does not appear in the other datasets
  filter(municipality != "Nawalparasi (Bardaghat Susta East)") |> 
  select(-province, -district, -municipality, -ward), 
  
  read_xlsx("./data/census/Rev_Gandaki_Hhld_QualityOfHouse_Ward_formated.xlsx", skip = 2) |> 
   setNames(c("province", "district", "municipality", "name", "ward", "house_quality_total",
             "house_quality_most_adequate_count", 
             "house_quality_adequate_count", 
             "house_quality_moderate_count", 
             "house_quality_inadequate_count", 
             "house_quality_least_adequate_count", 
             "house_quality_most_adequate_pc", 
             "house_quality_adequate_pc",
             "house_quality_moderate_pc", 
             "house_quality_inadequate_pc", 
             "house_quality_least_adequate_pc")) |> 
  gandaki_district_names() |> 
  filter(name %out% c("Gorkha", "Manang", "Mustang", "Myagdi", "Kaski",
                      "Lamjung", "Tanahu", "Nawalparasi East", "Syangja", "Parbat",
                      "Baglung", "NEPAL", "GANDAKI")) |> 
  select(-municipality) |> 
  rename(municipality = name) |> 
  # One extra municipality (electoral constituency, really)
  # That does not appear in the other datasets
  filter(municipality != "Nawalparasi (Bardaghat Susta East)") |> 
  mutate(ward = ifelse(ward == "Total", "All Wards", ward)) |> 
  select(-province, -district, -municipality, -ward)
  
  
  ) 
  
```



### Household - Bagmati-Gandaki combined

```{r census-combined-check}
bagmati |> 
  select(province, district, municipality, ward, contains("total")) |> 
  mutate(difference = ownership_total - foundation_total + 
           outer_wall_total - roof_total +
           floor_total - drinking_water_total +
           cooking_fuel_total - lighting_fuel_total + 
           toilet_total - hh_amenities_total + 
           wealth_quintile_total - house_quality_total) |> 
  filter(difference != 0)


gandaki |> 
  select(province, district, municipality, ward, contains("total")) |> 
  mutate(difference = ownership_total - foundation_total + 
           outer_wall_total - roof_total +
           floor_total - drinking_water_total +
           cooking_fuel_total - lighting_fuel_total + 
           toilet_total - hh_amenities_total + 
           wealth_quintile_total - house_quality_total) |> 
  filter(difference != 0)
  
```


```{r}
# Combining and cleaning place names to match the pcode dataset 
bagmati_gandaki_hhd <- rbind(
  bagmati, gandaki
) |> 
  mutate(district = ifelse(district == "Nawalparasi (East)", "Nawalparasi East", district)) |>
  mutate(municipality = str_remove_all(municipality, "Gaunpalika|Municipality"), 
         municipality = str_trim(municipality)) |> 
  mutate(municipality = case_when(
    municipality == "Melanchi" ~ "Melamchi", 
    municipality == "Kathmandu Metropolitian City" ~ "Kathmandu", 
    municipality == "Lalitpur Metropolitian City" ~ "Lalitpur", 
    municipality == "Hetauda Sub-Metropolitian City" ~ "Hetauda", 
    municipality == "Bharatpur Metropolitian City" ~ "Bharatpur", 
    municipality == "Manang Ngisyang" ~ "Ngisyang", 
    municipality == "Pokhara Metropolitian City" ~ "Pokhara", 
    TRUE ~ municipality
  )) |> 
  left_join(
    nepal_admin |> 
      filter(adm1_name %in% c("Bagmati", "Gandaki")) |> 
      distinct(adm1_name, adm1_pcode), 
    by = c("province" = "adm1_name")
  ) |> 
  left_join(
    nepal_admin |> 
      filter(adm1_name %in% c("Bagmati", "Gandaki")) |> 
      distinct(adm1_pcode, adm2_name, adm2_pcode), 
    by = c("adm1_pcode", "district" = "adm2_name")
  ) |> 
  left_join(
    nepal_admin |> 
      filter(adm1_name %in% c("Bagmati", "Gandaki")) |> 
      distinct(adm2_pcode, adm3_name, adm3_pcode), 
    by = c("adm2_pcode", "municipality" = "adm3_name")
  ) |> 
  rename(total_households = ownership_total) |> 
  select(-foundation_total, -outer_wall_total, -roof_total, -floor_total, 
         -drinking_water_total, -cooking_fuel_total, -lighting_fuel_total, 
         -toilet_total, -hh_amenities_total, -wealth_quintile_total, 
         -house_quality_total)
```


### Population - Bagmati


```{r}
read_xlsx("./data/census/WRD_Bagmati_Indv01-HouseholdAndPopulation.xlsx", skip = 2) |> 
  setNames(c("province", "district", "municipality", "ward", "total_households",
             "population_total", 
             "population_male",
             "population_female",
             "average_household_size", 
             "sex_ratio")) |> 
  ward_fill_filter() 
  
```

```{r}


read_xlsx("./data/census/WRD_Bagmati_Indv05-EconomicActivity.xlsx", skip = 2) |> 
  setNames(c("province", "district", "municipality", "ward", "sex", "total_population",
             "total_population_10_years_and_older",
             "economically_ative_usually_employed",
             "economically_active_usually_unemployed", 
             "not_usually_economically_active", 
             "not_economically_active", 
             "economic_activity_not_stated")) |> 
  ward_fill_filter2() |> 
  filter(!is.na(sex)) |> 
  mutate(sex = str_to_lower(sex)) |> 
  pivot_wider(
    names_from = c("sex"), 
    values_from = c("total_population",
                    "total_population_10_years_and_older", 
                    "economically_ative_usually_employed", 
                    "economically_active_usually_unemployed", 
                    "not_usually_economically_active", 
                    "not_economically_active"), 
    names_glue ="{sex}_{.value}"
  ) |> 
  glimpse()


```
```{r}
read_xlsx("./data/census/WRD_Bagmati_Indv02-FiveYearsAgeGroupsAndSex.xlsx", skip = 2) |> 
  setNames(c("province", "district", "municipality", "ward", 
             "five_year_age_group", 
             "total",
             "male", 
             "female")) |> 
  ward_fill_filter2() |> 
  filter(!is.na(five_year_age_group)) |> 
  mutate(five_year_age_group = str_replace(five_year_age_group, "-| ", "_"), 
         five_year_age_group = str_to_lower(five_year_age_group),
         five_year_age_group = str_replace(five_year_age_group, " yrs.", "_yrs"), 
         five_year_age_group = str_remove(five_year_age_group, "\\."), 
         five_year_age_group = str_replace(five_year_age_group, "\\+", "plus")) |> 
  pivot_wider(
    names_from = "five_year_age_group", 
    values_from = c("total", "male", "female"), 
    names_glue = "{.value}_{five_year_age_group}"
  ) 
```

```{r}
read_xlsx("./data/census/Indv_Bagmati_educationaStatusChild_Ward.xlsx", skip = 2) |> 
  setNames(
    c("province", "district", "municipality", "name", "ward",
      "total_children_5_17", 
      "male_children_5_17", 
      "female_children_5_17", 
      "currently_attending_school_male", 
      "currently_attending_school_female", 
      "oos_ever_attended_school_male", 
      "oos_ever_attended_school_female", 
      "oos_never_attended_school_male", 
      "oos_never_attended_school_female", 
      "currently_attending_school_total_pc", 
      "currently_attending_school_male_pc", 
      "currently_attending_school_female_pc", 
      "oos_ever_attended_school_total_pc", 
      "oos_ever_attended_school_male_pc", 
      "oos_ever_attended_school_female_pc", 
      "oos_never_attended_school_total_pc", 
      "oos_never_attended_school_male_pc", 
      "oos_never_attended_school_female_pc")
  ) |> 
  ward_fill_filter() |> 
  bagmati_district_names() |> 
  glimpse()
  
```



```{r}
read_xlsx("./data/census/Indv_Bagmati_Adultliteracy15plus_Ward.xlsx", skip = 2) |> 
  setNames(
    c("province", "district", "municipality", "name", "ward",
      "population_15plus_total",
      "population_15plus_male", 
      "population_15plus_female", 
      "literate_population_total", 
      "literate_population_male", 
      "literate_population_female", 
      "literacy_rate_total", 
      "literacy_rate_male", 
      "literacy_rate_female"
      )
  ) |> 
  ward_fill_filter() |> 
  bagmati_district_names() |>
  glimpse()
  
```

```{r}
read_xlsx("./data/census/Indv_Bagmati_BroadAge_dependency_ward.xlsx", skip = 2) |> 
  setNames(c("province", "district", "municipality", "name", "ward",
             "population_0_14", 
             "population_15_64", 
             "population_65plus", 
             "total_population", 
             "child_dependency_ratio", 
             "elderly_dependency_ratio",  
             "total_dependency_ratio")) |> 
  ward_fill_filter() |> 
  bagmati_district_names() |> 
  glimpse()
```
```{r}
read_xlsx("./data/census/Indv_Bagmati_educationalLevel_Ward.xlsx", skip = 2) |> 
  setNames(c("province", "district", "municipality", "name", "ward",
             "population_5plus_total", 
             "population_5plus_male", 
             "population_5plus_female", 
             "education_level_illiterate_male", 
             "education_level_illiterate_female", 
             "education_level_early_childhood_male", 
             "education_level_early_childhood_female", 
             "education_level_basic_level_male", 
             "education_level_basic_level_female", 
             "education_level_secondary_male", 
             "education_level_secondary_female", 
             "education_level_higher_education_male", 
             "education_level_higher_education_female", 
             "education_level_other_male", 
             "education_level_other_female", 
             "education_level_illiterate_pc_total", 
             "education_level_illiterate_pc_male", 
             "education_level_illiterate_pc_female", 
             "education_level_early_childhood_pc_total", 
             "education_level_early_childhood_pc_male", 
             "education_level_early_childhood_pc_female", 
             "education_level_basic_level_pc_total", 
             "education_level_basic_level_pc_male", 
             "education_level_basic_level_pc_female", 
             "education_level_secondary_pc_total", 
             "education_level_secondary_pc_male", 
             "education_level_secondary_pc_female", 
             "education_level_higher_education_pc_total",
             "education_level_higher_education_pc_male", 
             "education_level_higher_education_pc_female", 
             "education_level_other_pc_total", 
             "education_level_other_pc_male", 
             "education_level_other_pc_female"
             )) |> 
  ward_fill_filter() |> 
  bagmati_district_names() |> 
  glimpse()
```


```{r}
affected_wards |> 
  select(adm2_en, adm2_pcode, adm3_en, new_ward_n) |> 
  left_join(nepal_admin |> 
              distinct(adm1_name, adm2_pcode), 
            by = "adm2_pcode") |> 
  select(adm1_en = adm1_name, adm2_en, adm3_en, ward_number = new_ward_n) |> 
  count(adm1_en)
  write_csv("./data/locations_assessment_registry.csv")

nepal_admin |> 
  filter(adm1_name %in% c("Bagmati", "Gandaki")) |> 
  distinct(adm1_name, adm2_name, adm3_name, adm1_pcode, adm2_pcode, adm3_pcode) |> 
  write_csv("./data/locations_assessment_registry.csv")
 
```



```{r}

affected_wards_population |> 
  mutate(count = 1) |> 
  group_by(district) |> 
  summarise(municipalities = n_distinct(adm3_pcode), 
            municipalities_emergency = sum(count[emergency_declared == "Yes"], na.rm = TRUE), 
            affected_population = sum(estimated_affected_population)) |> 
  rename(`Affected Population` = affected_population, 
         `Municipalities declared emergency` = municipalities_emergency, 
         District = district, 
         Municipalities = municipalities) |> 
  arrange(desc(`Affected Population`)) |> 
  flextable() %>% 
  set_caption(caption = "Affected population by municipality") %>% 
  theme_zebra() |> 
  save_as_image("./plots/affected_population_municipality.png")
```

## 5Ws


```{r}
consolidated <- read_xlsx("./data/NEPAL Consolidated Data (for dashboard) 20260907.xlsx", 
                          sheet = "Consolidated_Data") |> 
  janitor::clean_names() |> 
  mutate_at(c("province", "district", "municipality"), ~ str_to_title(.)) |> 
  mutate_at(c("province", "district", "municipality"), ~ str_trim(.)) |> 
  mutate(municipality = str_remove_all(municipality, " Gaunpalika")) |> 
  mutate(province = case_when(
    district == "Gorkha" ~ "Gandaki", 
    district == "Tanahu" ~ "Gandaki",
    TRUE ~ province
  )) |> 
  mutate(district = case_when(
    municipality == "Gosaikunda" ~ "Rasuwa", 
    municipality == "Bidur Municipality" ~ "Nuwakot", 
    TRUE ~ district
  )) |> 
  mutate(municipality = case_when(
    municipality == "Benighat" ~ "Benighat Rorang", 
    municipality == "Galchi Rural Municipality" ~ "Galchhi", 
    municipality == "Gandaki" ~ "Gandaki", 
    municipality == "Bheri Malika Municipality" ~ "Bheri Malika", 
    municipality == "Nalgad Municipality" ~ "Nalgad", 
    municipality == "Kathmandu Metropolitian City" ~ "Kathmandu", 
    municipality == "Nagarjun Municipality" ~ "Nagarjun", 
    municipality == "Belkotgadhi Municipality|Belkotgadhi Nagarpalika" ~ "Belkotgadhi", 
    str_detect(municipality, "Bidur") ~ "Bidur", 
    municipality == "Kispang Municipality" ~ "Kispang", 
    municipality == "Tarkeshwor" ~ "Tarakeshwor", 
    municipality == "Rasuwa Dao, Dhunche" ~ "Gosaikunda",
    str_detect(municipality, "Devghat") ~ "Devghat", 
    str_detect(municipality, "Gandaki") ~ "Gandaki", 
    str_detect(municipality, "Belkotgadhi") ~ "Belkotgadhi", 
    municipality == "Aanbukhaireni" ~ "Aanbu Khaireni",
    TRUE ~ municipality)) |> 
  left_join(
    nepal_admin |> 
      distinct(adm1_name, adm1_pcode), 
    by = c("province" = "adm1_name")
  ) |> 
  left_join(
    nepal_admin |> 
      distinct(adm1_pcode, adm2_name, adm2_pcode), 
    by = c("adm1_pcode", "district" = "adm2_name")
  ) |> 
  left_join(
    nepal_admin |> 
      distinct(adm1_pcode, adm2_pcode, 
             adm3_name, adm3_pcode), 
    by = c("adm1_pcode", "adm2_pcode", "municipality" = "adm3_name")
  ) |> 
  rename(individuals_reached = total_number_of_beneficiaries_reached_people_individuals)

```

### Planned/Reached Municipality

```{r planned-reach-municipality, fig.height=8}
consolidated |> 
  mutate(sector = ifelse(str_detect(sector, "Protection"), "Protection", sector), 
         sector = ifelse(str_detect(sector, "Health"), "Health", sector)) |> 
  filter(sector %out% c("ETC", "Logistics") & !is.na(sector)) |> 
  filter(province != "Karnali") |>
  # Remember to allow Kathmandu back in when they have more people who have been reached
  filter(district != "Kathmandu") |> 
  group_by(province, district, municipality, sector, adm3_pcode) |> 
  summarise(
    individuals_targeted = sum(people_targeted_individuals, na.rm = TRUE), 
    individuals_reached = sum(individuals_reached, na.rm = TRUE), 
    .groups = "drop"
  ) |>  
  mutate(label = paste0(municipality, ", ", district)) |> 
  filter(individuals_targeted != 0 | 
           individuals_reached != 0) |> 
  mutate(individuals_targeted = 
           ifelse(individuals_targeted == 0 & individuals_reached != 0, 
                  individuals_reached, individuals_targeted)) |> 
  left_join(
    affected_wards_population |>
      group_by(adm3_pcode) |>
      summarise(
        estimated_affected_population = sum(estimated_affected_population, na.rm = TRUE)),
    by = "adm3_pcode") |> 
  pivot_longer(cols = c(individuals_targeted, 
                        individuals_reached, 
                        estimated_affected_population), 
               names_to = "variable", 
               values_to = "value") |> 
  mutate(variable = str_replace_all(variable, "_", " "), 
         variable = str_replace_all(variable, "individuals", "beneficiaries"), 
         variable = str_to_title(variable), 
         variable = fct_relevel(variable,
                                c("Beneficiaries Targeted", 
                                  "Beneficiaries Reached", 
                                  "Estimated Affected Population"))) |> 
  ggplot(aes(x = value, y = municipality)) + 
  geom_col(aes(fill = fct_rev(variable)), position = position_dodge()) + 
  scale_fill_brewer(palette = "BuPu", direction = -1) +
  # scale_fill_viridis_d() + 
  scale_x_continuous(labels = comma) + 
  facet_wrap(~district, scales = "free", 
             ncol = 2) +
  guides(fill = guide_legend(reverse = TRUE)) +
  labs(x = "",  
       y = "Municipality", 
       title = "Planned, Reached and Estimated Affected Population by Municipality",
       subtitle = "as of 20260907, figures listed are beneficiaries frequencies, not individuals; from the 5Ws", 
       fill = "") +
   theme(strip.background = element_rect(fill = "black"), 
         strip.text = element_text(size = 13), 
         axis.text.y = element_text(size = 13))
   
ggsave("./plots/planned_reached_municipality.png", height = 8, width = 12)
```



```{r}
consolidated |> 
  mutate(sector = ifelse(str_detect(sector, "Protection"), "Protection", sector), 
         sector = ifelse(str_detect(sector, "Health"), "Health", sector)) |> 
  filter(sector %out% c("ETC", "Logistics") & !is.na(sector)) |> 
  filter(province != "Karnali") |> 
  group_by(province, district, municipality, sector, adm3_pcode) |> 
  summarise(
    individuals_targeted = sum(people_targeted_individuals, na.rm = TRUE), 
    individuals_reached = sum(individuals_reached, na.rm = TRUE), 
    .groups = "drop"
  ) |>  
  mutate(label = paste0(district, ", ", municipality)) |> 
  filter(individuals_targeted != 0 | 
           individuals_reached != 0) |> 
  mutate(individuals_targeted = 
           ifelse(individuals_targeted == 0 & individuals_reached != 0, 
                  individuals_reached, individuals_targeted)) |> 
  left_join(
    affected_wards_population |>
      group_by(adm3_pcode) |>
      summarise(
        estimated_affected_population = sum(estimated_affected_population, na.rm = TRUE)),
    by = "adm3_pcode") |> 
  pivot_longer(cols = c(individuals_targeted, 
                        individuals_reached), 
               names_to = "variable", 
               values_to = "value") |> 
  mutate(variable = str_replace_all(variable, "_", " "), 
         variable = str_to_title(variable)) |> 
  ggplot(aes(x = value, y = label)) + 
  geom_col(aes(fill = variable), position = position_dodge()) + 
  scale_fill_viridis_d(begin = .5) + 
  scale_x_continuous(labels = comma) + 
  facet_wrap(~sector, scales = "free", 
             ncol = 1) +
  labs(x = "", 
       y = "Municipality and District", 
       title = "Planned, Reached and Estimated Affected Population by Municipality", 
       fill = "") +
   theme(strip.background = element_rect(fill = "black"), 
         title = element_text(size = 9))

ggsave("./plots/planned_reached_sectors.png", height = 11, width = 8)
  
```


```{r}
consolidated |> 
  filter(municipality == "Gosaikunda" & sector == "WASH") |> 
  group_by(sector) |> 
  summarise(individuals_reached = sum(individuals_reached, na.rm = TRUE), 
            individuals_targeted = sum(people_targeted_individuals, na.rm = TRUE))
```

### Sector agencies map

```{r}
consolidated |> 
  mutate(sector = ifelse(str_detect(sector, "Protection"), "Protection", sector), 
         sector = ifelse(str_detect(sector, "Health"), "Health", sector)) |> 
  filter(sector %out% c("ETC", "Logistics") & !is.na(sector)) |> 
  filter(province != "Karnali") |>
  group_by(district, adm2_pcode, municipality, adm3_pcode, sector, lead_agency, implementing_partner) |> 
  summarise(
    frequencies = sum(individuals_reached, na.rm = TRUE), 
    .groups = "drop"
  ) |> 
  mutate(duplicate = ifelse(
    implementing_partner == lead_agency, 
    1, 0
  )) |> 
  mutate(implementing_partner = ifelse(
    duplicate == 1, NA_character_, implementing_partner
  )) |> 
  pivot_longer(
    lead_agency:implementing_partner, 
    names_to = "role",
    values_to = "agencies"
  ) |> 
  select(-frequencies, -duplicate) |> 
  filter(!is.na(agencies)) |>  
  group_by(district, adm2_pcode, municipality, adm3_pcode, sector) |> 
  summarise(num_agencies = n_distinct(agencies), 
            agencies_text = paste(agencies, collapse = ",")) |> 
  right_join(
      adm3 |> filter(adm2_name %in% c("Dhading", "Nuwakot", "Gorkha", 
                                "Jajarkot", "Kathmandu", "Mugu", 
                                "Rasuwa", "Tanahu")), 
      by = c("adm2_pcode", "adm3_pcode")
  ) |> 
  filter(!is.na(municipality) & !is.na(sector)) |> 
  mutate(num_agencies = as.numeric(num_agencies)) |> 
  st_as_sf() |> 
  ggplot() +
  geom_sf(aes(fill = num_agencies), linewidth =.1) +
  geom_sf_text(aes(label = municipality), size = 2) +
  scale_fill_continuous(palette = "Blues", 
                        breaks = seq(1, 20, 2), 
                        guide = guide_colorbar(barheight = unit(6, "cm"))) +
  # scale_fill_viridis(direction = -1) + 
  facet_wrap(~sector) + 
  labs(title = "Number of agencies by sector, by municipality", 
       subtitle = "as of 202609076, from the 5Ws",
       x = "", y = "", 
       fill = "Number of\nagencies") + 
  theme(strip.background = element_rect(fill = "black"), 
        axis.text.x = element_text(size = 5), 
        axis.text.y = element_text(size = 5), 
        panel.grid.major = element_line(color = "gray90"),
        panel.grid.minor = element_line(color = "gray90"))
  
ggsave("./plots/sector_agencies_map_blues.png", height = 7, width = 11, units = "in")
```


```{r}
consolidated |> 
  filter(province != "Karnali") |> 
  group_by(response_modality) |> 
  summarise(individuals_reached = sum(individuals_reached, na.rm = TRUE)) |> 
  arrange(desc(individuals_reached)) |> 
  filter(individuals_reached != 0) |> 
  mutate(response_modality = ifelse(is.na(response_modality), 
                                    "N.A.", response_modality)) |> 
  mutate(pc = round(individuals_reached / sum(individuals_reached) * 100, 2)) |> 
  rename(`Response modality` = response_modality, 
         `Beneficiary frequencies` = individuals_reached, 
         `%` = pc) |> 
  flextable() |> 
  theme_zebra() |> 
  save_as_image("./plots/response_modality.png")

consolidated |> 
  filter(is.na(response_modality)) |> 
  count(activity_description, sort = TRUE)

consolidated |> filter(is.na(activity))
```


```{r}
consolidated |> 
  group_by(activity) |> 
  summarise(
    individuals_reached = sum(individuals_reached, na.rm = TRUE), 
    individuals_targeted = sum(people_targeted_individuals, na.rm = TRUE)
  ) |> 
  arrange(desc(individuals_reached)) |>
  rename(
    Activity = activity, 
    `Individuals reached` = individuals_reached, 
    `Individuals targeted` = individuals_targeted
  ) |> 
  head(10) |> 
  # mutate(activity = str_sub(activity, start = 1L, end = 70L)) |> 
  flextable() |> 
  flextable::set_caption(as_paragraph(as_chunk("Top 10 activities by individuals reached"))) |> 
  theme_zebra() |> 
  flextable::width(width = 3) |> 
  save_as_image("./plots/top_activities.png")
```


```{r}
adm3 |> filter(adm2_name %in% c("Dhading", "Nuwakot", "Gorkha", 
                                "Jajarkot", "Kathmandu", "Mugu", 
                                "Rasuwa", "Tanahu"))

adm3 |> 
  filter(adm1_name %in% c("Bagmati", "Gandaki")) |> 
  st_as_sf() |> 
  ggplot() +
  geom_sf(size = .1) + 
  geom_sf_text(aes(label = adm2_name), size = 1) +
  geom_sf_text(aes(label = adm3_name), size = 1.5)
  
```


## Contacts

```{r}
contact_list <- read_csv("./data/Nepal Flood Response Contact List - Contact List.csv", 
         skip = 2) |> 
  janitor::clean_names() |> 
  mutate(agency = case_when(
    str_detect(agency, "CWIN|cwin|Cwin|CWIN-|CWIM- NEPAL") ~ "CWIN-Nepal", 
    str_detect(agency, "DFAT|Australian Department of Foreign Affairs and Trade") ~ "DFAT", 
    str_detect(agency, "Habitat for Humanity") ~ "Habitat for Humanity", 
    str_detect(agency, "FAIR MED / MANK") ~ "MANK and FAIR MED", 
    str_detect(agency, "Nepal Red Cross Society|Nepal Redcross Society") ~ "Nepal Red Cross Society", 
    str_detect(agency, "OM ") ~ "Operation Mobilisation", 
    str_detect(agency, "Plan International") ~ "Plan International", 
    str_detect(agency, "Save the Children") ~ "Save the Children", 
    str_detect(agency, "UN Women") ~ "UN Women", 
    str_detect(agency, "UNESCO") ~ "UNESCO", 
    str_detect(agency, "UNFPA") ~ "UNFPA", 
    str_detect(agency, "UNODC") ~ "UNODC", 
    str_detect(agency, "Unicef") ~ "UNICEF", 
    str_detect(agency, "WFP|World Food Programme") ~ "WFP", 
    str_detect(agency, "World Health Organization") ~ "WHO", 
    str_detect(agency, "One heart worldwide") ~ "One Heart Worldwide", 
    TRUE ~ agency
  )) 

contact_list |> count(agency)

contact_list |> write_csv("./data/contact_list_agencies_cleaned_20260907.csv")
```


## Wards census

```{r}

```

